### ISSUE TITLE
mips64-elf-ld: cannot find -lkmc (linker flag)

### ISSUE THREAD

**Issue by ErikMN** [trhodeos/modern-n64sdk#1]
Hello!

I tried to build some of the official example code by setting up the tool-chain according to your instructions.
However it fails with the error:

`mips64-elf-ld: cannot find -lkmc`

Indeed in the `Makefile` for each example it uses the linker flag "lkmc":

`LDFLAGS =	$(MKDEPOPT)  -L$(ROOT)/usr/lib $(N64LIB) -L$(GCCDIR)/mipse/lib -lkmc`

If I remove this flag, it compiles but the output does not run in an emulator (I tried with output compiled using the original gcc and it works).

OS tried on: Debian/Ubuntu

Any suggestions?

Anyways I really like this project, building official n64 code using modern tools seems like a fun concept!

BR
ErikMN

**Comment by trhodeos** [comment]
Hi!

I am about to be off-the-grid for a week and am not able to update the docs before I leave. However, I think I know what the problem is:
- The dirs in $GCCDIR are actually upper-case
- OS X's HFS+ is case insensitive by default (that why this code works for me)
- ext3/ext4/most sane filesystems are case sensitive. 
- Try updating ROOT and GCCDIR to point to the correct case-sensitive dirs.
- You may need to move LIBKMC.A (or whatever the file is in $GCCDIR/MIPSE/LIB) to be lowercase (for example libkmc.a). I'm not sure how gcc handles uppercase 'lib' prefixes.

Let me know if you get something working. If not, I'll try to investigate some more once I get back.

**Comment by ErikMN** [comment]
Hello again!

I got it to working by renaming the entire MIPSE and all subdirs in it to lowercase.
When looking at my previous post I can see that the error message actually is giving the path in lowercase..

Awesome!
Thx for the support.
